package system

// routeDescriptions 为每个接口提供唯一、准确的中文说明。
// routeDescription() 会优先查表，未命中时再回退到内置开关逻辑。
var routeDescriptions = map[string]string{
	// ===== 基础 =====
	"/health":               "服务健康检查与版本状态",
	"/api/migration/status": "读取迁移状态、路由归属与废弃模块清单",

	// ===== 认证 =====
	"/api/auth/2fa/status":           "查询当前是否已启用双因子认证",
	"/api/auth/login-options":        "获取当前可用的登录方式（密码 / GitHub / 通行密钥）",
	"/api/auth/plugin-pairings/claim": "用一次性配对码换取浏览器插件登录凭据",
	"/api/auth/github/config":        "读取或保存 GitHub OAuth 登录配置",
	"/api/auth/github/start":         "发起 GitHub OAuth 登录跳转",
	"/api/auth/github/callback":      "处理 GitHub OAuth 回调并建立登录会话",
	"/api/auth/github/2fa":           "完成 GitHub 登录后的二次验证",
	"/api/auth/2fa":                  "双因子认证启用状态总入口",
	"/api/auth/webauthn/credentials": "列出或删除已绑定的通行密钥",
	"/api/auth/webauthn/register":    "发起或完成通行密钥注册",
	"/api/auth/webauthn/login":       "发起或完成通行密钥登录",
	"/api/auth":                      "认证相关操作总入口（会话校验等）",
	"/api/auth/check-password":       "检查是否已设置管理员密码及是否处于演示模式",
	"/api/auth/session":              "校验当前浏览器会话是否已登录",
	"/api/auth/login":                "管理员密码登录，可附带 2FA 一次性验证码",
	"/api/auth/logout":               "销毁当前登录会话并清理认证状态",
	"/api/auth/set-password":         "首次初始化系统管理员密码",
	"/api/auth/verify-password":      "敏感操作前再次验证管理员密码",
	"/api/auth/change-password":      "修改管理员密码，需同时提交旧密码与新密码",
	"/api/auth/2fa/setup":            "生成 2FA 初始化所需的密钥与二维码数据",
	"/api/auth/2fa/enable":           "使用 setup 密钥和验证码正式启用 2FA",
	"/api/auth/2fa/disable":          "关闭 2FA 保护，需管理员密码确认",

	// ===== 系统设置 =====
	"/api/settings":                    "读取或保存系统运行配置",
	"/api/settings/operation-logs":     "读取系统操作日志",
	"/api/settings/sys-logs":           "读取系统运行日志",
	"/api/settings/app-log-file":       "读取应用日志文件内容",
	"/api/settings/log-settings":       "读取或更新日志保留与轮转策略",
	"/api/settings/enforce-log-limits": "立即执行日志大小上限清理",
	"/api/settings/clear-logs":         "清空系统日志",
	"/api/settings/clear-app-logs":     "清空应用日志",
	"/api/settings/site-brand/icons/{id}": "读取或删除单个站点品牌图标",
	"/api/settings/site-brand/icons":   "列出或上传站点品牌图标",
	"/api/settings/database-stats":     "统计数据库大小、表结构与行数",
	"/api/settings/database-analysis":  "分析数据库表健康度与潜在问题",
	"/api/settings/deprecated-tables":  "检测已废弃的历史数据表",
	"/api/settings/cleanup-deprecated-tables": "清理废弃表（清理前自动备份数据库）",
	"/api/settings/database/import":    "上传并导入 SQLite 数据库文件",
	"/api/settings/database/import/preview": "上传数据库文件并生成导入分析结果，不覆盖当前库",
	"/api/settings/database/import/commit":  "根据 preview 返回的导入令牌提交数据库替换",
	"/api/settings/export-database":    "导出当前数据库文件",
	"/api/settings/migration-self-check": "执行数据库迁移自检",
	"/api/settings/vacuum-database":    "对数据库执行 VACUUM 压缩回收空间",

	// ===== 系统 =====
	"/api/system/host-metrics":     "读取本机 CPU / 内存 / 磁盘实时指标",
	"/api/system/api-stats":        "读取 API 调用次数与耗时统计",
	"/api/system/api-docs":         "读取系统自动生成的接口文档清单",
	"/api/system/openapi.json":     "导出 OpenAPI 3.1 接口文档",
	"/api/openapi.json":            "导出 OpenAPI 3.1 接口文档",
	"/api/api-keys":                "管理 API 密钥的生命周期与权限范围",
	"/api/system/api-keys":         "管理 API 密钥（系统路径）",
	"/api/system/api-keys/{id}":    "更新、撤销或轮换单个 API 密钥",
	"/api/system/logs/stream":      "实时流式读取系统日志",
	"/api/system/logs/download":    "下载系统日志文件",

	// ===== AI 接入 =====
	"/api/system/ai-access":                 "读取 AI 接入概览（Agent Key、端点、策略）",
	"/api/system/ai-access/key/rotate":      "轮换 AI Agent Key",
	"/api/system/ai-access/write":           "开启或关闭 AI 写操作权限",
	"/api/system/ai-access/audit":           "分页查询 AI 接入调用审计",
	"/api/system/ai-access/audit/clear":     "清空 AI 接入调用审计记录",
	"/api/system/ai-access/mcp-servers":     "列出或新增 MCP 服务配置",
	"/api/system/ai-access/mcp-servers/{id}": "更新或删除单个 MCP 服务配置",
	"/api/system/ai-access/skills":          "列出或新增 Skill 配置",
	"/api/system/ai-access/skills/{id}":     "更新或删除单个 Skill 配置",
	"/api/ai-access":                        "读取 AI 接入概览（别名路径）",
	"/api/ai-access/key/rotate":             "轮换 AI Agent Key（别名路径）",
	"/api/ai-access/write":                  "开启或关闭 AI 写操作权限（别名路径）",
	"/api/ai-access/audit":                  "分页查询 AI 接入调用审计（别名路径）",
	"/api/ai-access/audit/clear":            "清空 AI 接入调用审计记录（别名路径）",
	"/api/ai-access/mcp-servers":            "列出或新增 MCP 服务配置（别名路径）",
	"/api/ai-access/mcp-servers/{id}":       "更新或删除单个 MCP 服务配置（别名路径）",
	"/api/ai-access/skills":                 "列出或新增 Skill 配置（别名路径）",
	"/api/ai-access/skills/{id}":            "更新或删除单个 Skill 配置（别名路径）",
	"/api/ai/manifest":                      "供外部 AI 客户端读取系统接入能力清单",
	"/api/ai/mcp":                           "供外部 AI 客户端通过 MCP 调用系统工具",

	// ===== 双因子认证 =====
	"/api/totp":               "TOTP 双因子认证账户管理总入口",
	"/api/totp/accounts":      "列出或新增 TOTP 账户",
	"/api/totp/accounts/{id}": "更新、删除或递增单个 TOTP 账户",
	"/api/totp/groups":        "列出或新增 TOTP 分组",
	"/api/totp/groups/{id}":   "更新或删除 TOTP 分组",

	// ===== 文件柜 =====
	"/api/filebox":                "文件柜上传、下载与条目管理总入口",
	"/api/filebox/shares":         "查询当前用户的分享条目列表（含下载次数、有效期）",
	"/api/filebox/settings":       "读取或更新文件柜设置（公开上传、大小限制）",
	"/api/filebox/share":          "为文件生成分享链接",
	"/api/filebox/void/rooms":     "创建空房间（匿名协作）",
	"/api/filebox/void/rooms/{roomId}": "查询或关闭空房间",
	"/api/filebox/void/rooms/{roomId}/participants": "查询或管理房间参与者",

	// ===== 可用性监测 =====
	"/api/uptime":              "可用性监测与状态页管理总入口",
	"/api/uptime/monitors":     "列出或新增监测项",
	"/api/uptime/monitors/{id}": "更新、删除或启停单个监测项",

	// ===== 通知中心 =====
	"/api/notification":          "通知中心渠道与规则管理总入口",
	"/api/notification/channels": "列出或新增通知渠道",
	"/api/notification/channels/{id}": "更新、删除或测试单个通知渠道",
	"/api/notification/rules":    "列出或新增通知规则",
	"/api/notification/rules/{id}": "更新、删除、启用或禁用通知规则",

	// ===== 定时任务 =====
	"/api/scheduler":                    "工作流调度管理总入口",
	"/api/scheduler/cron/preview":       "预览 cron 表达式的下次执行时间",
	"/api/scheduler/tasks":              "列出或新增定时任务",
	"/api/scheduler/tasks/{id}":         "更新或删除定时任务",
	"/api/scheduler/nodes":              "列出或更新调度节点",
	"/api/scheduler/nodes/{id}":         "更新或删除调度节点",
	"/api/scheduler/workflows":          "列出或新增工作流",
	"/api/scheduler/workflows/export":   "导出工作流定义",
	"/api/scheduler/workflows/import":   "导入工作流定义",
	"/api/scheduler/workflows/{id}/run": "手动触发工作流运行",
	"/api/scheduler/workflow-runs/{id}/retry": "重试失败的工作流运行",
	"/api/scheduler/workflow-runs/{id}/cancel": "取消进行中的工作流运行",
	"/api/cron":                         "定时任务管理总入口",
	"/api/cron/tasks":                   "列出或新增 cron 任务",
	"/api/cron/tasks/{id}":              "更新或删除 cron 任务",
	"/api/cron/logs":                    "查看或清理 cron 执行日志",

	// ===== 备份 =====
	"/api/backup":         "备份任务与恢复管理总入口",
	"/api/backup/configs": "读取或保存备份配置（本地 / OSS / COS / S3）",
	"/api/backup/run":     "手动触发一次备份",
	"/api/backup/restore": "从指定备份恢复数据库（需 confirm=RESTORE）",

	// ===== Cloudflare =====
	"/api/cloudflare/accounts":                         "列出或新增 Cloudflare 账号",
	"/api/cloudflare/accounts/{id}":                    "更新或删除 Cloudflare 账号",
	"/api/cloudflare/accounts/export":                  "导出已保存的 Cloudflare 账号",
	"/api/cloudflare/export/accounts":                  "导出 Cloudflare 账号（旧路径）",
	"/api/cloudflare/import/accounts":                  "批量导入 Cloudflare 账号",
	"/api/cloudflare/accounts/{id}/verify":             "验证账号 Token 是否有效",
	"/api/cloudflare/accounts/{id}/token":              "读取账号 Token（敏感，请谨慎调用）",
	"/api/cloudflare/accounts/{id}/cf-account-id":      "查询账号对应的 Cloudflare Account ID",
	"/api/cloudflare/accounts/{id}/zones":              "列出或新增域名 Zone",
	"/api/cloudflare/accounts/{accountId}/zones/{zoneId}": "删除指定域名 Zone",
	"/api/cloudflare/zones":                            "聚合列出所有账号下的 Zone",
	"/api/cloudflare/record-types":                     "获取 Cloudflare 支持的 DNS 记录类型",
	"/api/cloudflare/accounts/{accountId}/zones/{zoneId}/records": "列出或新增 DNS 记录",
	"/api/cloudflare/accounts/{accountId}/zones/{zoneId}/records/{recordId}": "更新或删除单条 DNS 记录",
	"/api/cloudflare/accounts/{accountId}/zones/{zoneId}/batch": "批量创建 DNS 记录",
	"/api/cloudflare/accounts/{accountId}/zones/{zoneId}/purge": "清除 Zone 的缓存",
	"/api/cloudflare/accounts/{accountId}/zones/{zoneId}/ssl": "读取或更新 SSL / TLS 设置",
	"/api/cloudflare/accounts/{accountId}/zones/{zoneId}/analytics": "读取 Zone 的流量分析数据",
	"/api/cloudflare/accounts/{accountId}/zones/{zoneId}/switch": "快速切换 Zone 的 DNS 内容",
	"/api/cloudflare/accounts/{accountId}/zones/{zoneId}/workers/routes": "列出或新增 Worker 路由",
	"/api/cloudflare/accounts/{accountId}/zones/{zoneId}/workers/routes/{routeId}": "更新或删除 Worker 路由",
	"/api/cloudflare/accounts/{id}/workers":            "列出账号下的 Worker 脚本",
	"/api/cloudflare/accounts/{id}/workers/{scriptName}": "读取、更新或删除 Worker 脚本",
	"/api/cloudflare/accounts/{id}/workers/{scriptName}/toggle": "启用或停用 Worker",
	"/api/cloudflare/accounts/{id}/workers/{scriptName}/analytics": "读取 Worker 的调用分析",
	"/api/cloudflare/accounts/{id}/workers/{scriptName}/domains": "列出或绑定 Worker 自定义域名",
	"/api/cloudflare/accounts/{id}/workers/{scriptName}/domains/{domainId}": "解绑 Worker 自定义域名",
	"/api/cloudflare/accounts/{id}/pages":              "列出 Cloudflare Pages 项目",
	"/api/cloudflare/accounts/{id}/pages/{projectName}": "删除 Pages 项目",
	"/api/cloudflare/accounts/{id}/pages/{projectName}/deployments": "列出项目的部署记录",
	"/api/cloudflare/accounts/{id}/pages/{projectName}/deployments/{deploymentId}": "删除指定部署",
	"/api/cloudflare/accounts/{id}/pages/{projectName}/domains": "列出或新增 Pages 自定义域名",
	"/api/cloudflare/accounts/{id}/pages/{projectName}/domains/{domain}": "删除 Pages 自定义域名",
	"/api/cloudflare/accounts/{accountId}/r2/buckets":  "列出或新建 R2 存储桶",
	"/api/cloudflare/accounts/{accountId}/r2/metrics": "获取 R2 账号级存储用量与对象数量",
	"/api/cloudflare/accounts/{accountId}/r2/buckets/{bucketName}": "删除 R2 存储桶",
	"/api/cloudflare/accounts/{accountId}/r2/buckets/{bucketName}/objects": "列出存储桶内的对象",
	"/api/cloudflare/accounts/{accountId}/r2/buckets/{bucketName}/objects/{objectKey}": "删除 R2 对象",
	"/api/cloudflare/accounts/{accountId}/r2/buckets/{bucketName}/objects/{objectKey}/download-info": "获取 R2 对象的下载信息",
	"/api/cloudflare/accounts/{accountId}/r2/buckets/{bucketName}/objects/{objectKey}/download": "下载 R2 对象",
	"/api/cloudflare/accounts/{accountId}/r2/buckets/{bucketName}/objects/folder-download": "打包下载 R2 目录（zip）",
	"/api/cloudflare/accounts/{accountId}/r2/buckets/{bucketName}/objects/{objectKey}/preview": "预览 R2 对象内容",
	"/api/cloudflare/accounts/{id}/tunnels":            "列出或新建 Tunnel",
	"/api/cloudflare/accounts/{accountId}/tunnels/{tunnelId}": "查询、更新或删除 Tunnel",
	"/api/cloudflare/accounts/{accountId}/tunnels/{tunnelId}/configuration": "读取或更新 Tunnel 配置",
	"/api/cloudflare/accounts/{accountId}/tunnels/{tunnelId}/token": "获取 Tunnel 运行 Token",
	"/api/cloudflare/accounts/{accountId}/tunnels/{tunnelId}/connections": "查询 Tunnel 的连接状态",
	"/api/cloudflare/templates":                        "列出或新增 DNS 模板",
	"/api/cloudflare/templates/{id}":                   "更新或删除 DNS 模板",
	"/api/cloudflare/templates/{templateId}/apply":     "将 DNS 模板应用到指定 Zone",
	"/api/cloudflare/import/templates":                 "批量导入 DNS 模板",

	// ===== 阿里云 =====
	"/api/aliyun":                                 "阿里云账号与资源管理总入口",
	"/api/aliyun/accounts":                        "列出或新增阿里云账号",
	"/api/aliyun/accounts/{id}":                   "更新或删除阿里云账号",
	"/api/aliyun/accounts/{id}/metrics":           "读取账号下云监控指标",
	"/api/aliyun/accounts/{id}/domains":           "列出或添加域名",
	"/api/aliyun/accounts/{id}/domains/{domainName}": "删除域名",
	"/api/aliyun/accounts/{id}/domains/{domainName}/records": "列出或新增 DNS 记录",
	"/api/aliyun/accounts/{id}/records/{recordId}": "更新或删除 DNS 记录",
	"/api/aliyun/accounts/{id}/records/{recordId}/status": "启用或停用 DNS 记录",
	"/api/aliyun/accounts/{id}/instances":         "列出 ECS 实例",
	"/api/aliyun/accounts/{id}/instances/{instanceId}/{action}": "对 ECS 实例执行启停等动作",
	"/api/aliyun/accounts/{id}/swas":              "列出轻量应用服务器",
	"/api/aliyun/accounts/{id}/swas/{instanceId}/firewall": "列出或新增防火墙规则",
	"/api/aliyun/accounts/{id}/swas/{instanceId}/firewall/{ruleId}": "删除防火墙规则",
	"/api/aliyun/accounts/{id}/swas/{instanceId}/{action}": "对轻量服务器执行启停等动作",

	// ===== 腾讯云 =====
	"/api/tencent":                                 "腾讯云账号与资源管理总入口",
	"/api/tencent/accounts":                        "列出或新增腾讯云账号",
	"/api/tencent/accounts/{id}":                   "更新或删除腾讯云账号",
	"/api/tencent/accounts/{id}/domains":           "列出或添加域名",
	"/api/tencent/accounts/{id}/domains/{domain}/records": "列出或新增 DNS 记录",
	"/api/tencent/accounts/{id}/domains/{domain}/records/{recordId}": "更新或删除 DNS 记录",
	"/api/tencent/accounts/{id}/domains/{domain}/records/{recordId}/status": "启用或停用 DNS 记录",
	"/api/tencent/accounts/{id}/cvm":               "列出 CVM 实例",
	"/api/tencent/accounts/{id}/cvm/{instanceId}/control": "对 CVM 实例执行控制动作",
	"/api/tencent/accounts/{id}/lighthouse":        "列出轻量应用服务器",
	"/api/tencent/accounts/{id}/lighthouse/{instanceId}/control": "对轻量服务器执行控制动作",

	// ===== 甲骨文云 / Microsoft 365 =====
	"/api/oracle":                "Oracle OCI 账号与实例管理总入口",
	"/api/m365":                  "Microsoft 365 租户、用户、组与许可证管理",
	"/api/m365/registrations":    "查询公开注册记录（用户自助注册结果）",
	"/api/m365/public/register":  "提交 Microsoft 365 公开注册申请",
	"/api/m365/public/invites/{code}": "查询邀请码对应的注册详情",

	// ===== Fly.io / Koyeb =====
	"/api/flyio":                    "Fly.io 应用部署管理总入口",
	"/api/flyio/accounts":           "列出或新增 Fly.io 账号",
	"/api/flyio/accounts/export":    "导出 Fly.io 账号",
	"/api/flyio/accounts/{id}":      "删除 Fly.io 账号",
	"/api/flyio/accounts/{id}/update-all-images": "批量更新账号下所有应用镜像",
	"/api/flyio/proxy/apps":         "聚合列出账号下的全部应用",
	"/api/flyio/apps":               "列出或新建应用",
	"/api/flyio/apps/{appName}":     "删除应用",
	"/api/flyio/apps/{appName}/rename": "重命名应用",
	"/api/flyio/apps/{appName}/redeploy": "重新部署应用（重启机器）",
	"/api/flyio/apps/{appName}/update-image": "更新应用镜像，镜像未变化时返回「已是最新」",
	"/api/flyio/apps/{appName}/machines": "列出应用的机器",
	"/api/flyio/apps/{appName}/events": "读取应用部署事件",
	"/api/flyio/apps/{appName}/config": "读取或更新应用配置",
	"/api/flyio/apps/{appName}/logs": "读取应用日志",
	"/api/koyeb":                    "Koyeb 应用部署管理总入口",
	"/api/koyeb/accounts":           "列出或新增 Koyeb 账号",
	"/api/koyeb/accounts/export":    "导出 Koyeb 账号",
	"/api/koyeb/accounts/{id}":      "删除 Koyeb 账号",
	"/api/koyeb/accounts/{id}/refresh": "刷新账号下的应用与服务数据",
	"/api/koyeb/data":               "聚合读取账号数据",
	"/api/koyeb/services/{serviceId}": "删除服务",
	"/api/koyeb/services/{serviceId}/pause": "暂停服务",
	"/api/koyeb/services/{serviceId}/restart": "重启服务",
	"/api/koyeb/services/{serviceId}/redeploy": "重新部署服务",
	"/api/koyeb/services/{serviceId}/rename": "重命名服务",
	"/api/koyeb/services/{serviceId}/logs": "读取服务日志",
	"/api/koyeb/services/{serviceId}/logs/tail": "实时跟随服务日志（SSE 流）",
	"/api/koyeb/services/{serviceId}/instances": "列出服务实例",
	"/api/koyeb/services/{serviceId}/metrics": "读取服务指标",
	"/api/koyeb/apps/{appId}":       "删除应用",
	"/api/koyeb/apps/{appId}/rename": "重命名应用",
	"/api/koyeb/usage":              "读取 Koyeb 用量统计",
	"/api/koyeb/usage/details":      "分页读取 Koyeb 组织用量明细",
	"/api/koyeb/services":           "创建 Koyeb 服务（需 appId/name/definition）",
	"/api/koyeb/services/{serviceId}/update": "更新服务镜像或运行配置（image/env/ports/regions/instanceType）并触发部署",
	"/api/koyeb/services/{serviceId}/deployments": "列出服务的部署记录（可 statuses 过滤）",
	"/api/koyeb/deployments/{deploymentId}/cancel": "取消进行中的部署",
	"/api/koyeb/services/{serviceId}/scale": "手动扩容配置读取/设置/重置",
	"/api/koyeb/apps/{appId}/pause": "暂停应用（含其下全部服务）",
	"/api/koyeb/apps/{appId}/resume": "恢复应用",
	"/api/koyeb/domains":           "列出或绑定 Koyeb 域名",
	"/api/koyeb/domains/{domainId}": "删除 Koyeb 域名",
	"/api/koyeb/domains/{domainId}/refresh": "刷新域名校验状态",
	"/api/koyeb/secrets":           "列出或新增 Koyeb 密钥",
	"/api/koyeb/secrets/{secretId}": "删除 Koyeb 密钥",
	"/api/koyeb/secrets/{secretId}/update": "更新 Koyeb 密钥值",
	"/api/koyeb/catalog/instances": "读取 Koyeb 实例规格目录",
	"/api/koyeb/catalog/regions":   "读取 Koyeb 可用区域目录",

	// ===== 1Panel 快捷控制 =====
	"/api/onepanel":                    "1Panel 服务器管理面板快捷控制总入口",
	"/api/onepanel/config":             "列出或新增 1Panel 连接配置（serverId / apiKey / baseUrl）",
	"/api/onepanel/spec":               "读取内置的 1Panel 官方 API 目录（717 个端点，供通用代理使用）",
	"/api/onepanel/config/{serverId}":  "更新或删除指定服务器的 1Panel 连接配置",
	"/api/onepanel/{serverId}/health":  "检查指定服务器上的 1Panel 面板连通性",
	"/api/onepanel/{serverId}/overview": "聚合读取面板状态、网站、容器与 OpenResty 摘要",
	"/api/onepanel/{serverId}/dashboard/current": "读取面板实时资源监控（CPU / 内存 / 磁盘 / 网络）",
	"/api/onepanel/{serverId}/upgrade/check":     "检查 1Panel 面板是否有可升级版本",
	"/api/onepanel/{serverId}/upgrade":           "升级 1Panel 面板到指定版本",
	"/api/onepanel/{serverId}/websites":          "列出网站或创建网站",
	"/api/onepanel/{serverId}/websites/{id}":     "读取或删除网站",
	"/api/onepanel/{serverId}/websites/{id}/operate": "启停或重启网站（start / stop / restart）",
	"/api/onepanel/{serverId}/websites/{id}/proxy":   "更新网站反向代理配置",
	"/api/onepanel/{serverId}/websites/{id}/https":   "启用或配置网站 HTTPS",
	"/api/onepanel/{serverId}/websites/{id}/nginx":   "更新网站 nginx 配置",
	"/api/onepanel/{serverId}/apps":             "查询应用市场（可安装应用）",
	"/api/onepanel/{serverId}/apps/install":     "安装应用（支持 dockerCompose）",
	"/api/onepanel/{serverId}/apps/installed":   "列出已安装应用",
	"/api/onepanel/{serverId}/apps/installed/{appInstallId}/op": "启动 / 停止 / 重启已安装应用",
	"/api/onepanel/{serverId}/containers":               "列出容器",
	"/api/onepanel/{serverId}/containers/operate":       "批量启停或重启容器",
	"/api/onepanel/{serverId}/containers/{name}/logs":   "读取容器日志",
	"/api/onepanel/{serverId}/containers/compose":       "创建 Compose 应用",
	"/api/onepanel/{serverId}/ssl":              "列出 SSL 证书",
	"/api/onepanel/{serverId}/ssl/obtain":       "为网站申请 SSL 证书（ACME）",
	"/api/onepanel/{serverId}/acme":             "创建网站 ACME 账号",
	"/api/onepanel/{serverId}/openresty/status": "读取 OpenResty 状态与连接数",
	"/api/onepanel/{serverId}/openresty/reload": "校验并重载 OpenResty 配置",
	"/api/onepanel/{serverId}/backup":           "立即执行备份",
	"/api/onepanel/{serverId}/backups/records":  "查询备份记录",
	"/api/onepanel/{serverId}/backups/options":  "读取备份存储账号",
	"/api/onepanel/{serverId}/databases":        "列出或创建数据库",
	"/api/onepanel/{serverId}/databases/{id}/password": "修改数据库密码",
	"/api/onepanel/{serverId}/databases/{id}":           "删除数据库",
	"/api/onepanel/{serverId}/runtimes":         "列出或创建运行环境（PHP / Node）",
	"/api/onepanel/{serverId}/cronjobs":         "列出或创建定时任务",
	"/api/onepanel/{serverId}/proxy":            "通用代理：直接调用任意 1Panel API",
	"/api/onepanel/{serverId}/proxy/catalog":    "读取内置 1Panel 官方 API 目录",

	// ===== GitHub =====
	"/api/github":                    "GitHub 仓库观测与 Actions 操作总入口",
	"/api/github/webhook":            "接收 GitHub Webhook 回调",
	"/api/github/webhook/{repositoryId}": "接收指定仓库的 Webhook 回调",
	"/api/github/events/stream":      "实时流式读取 GitHub 事件",
	"/api/github/public-pages":       "列出或新建公开页面",
	"/api/github/public-pages/{id}":  "更新或删除公开页面",
	"/api/github/public/page-by-domain": "按域名查找公开页面",
	"/api/github/public/pages/{slug}": "按 slug 读取公开页面",
	"/api/github/public/pages/{slug}/stream": "实时流式读取公开页面事件",
	"/api/github/public/pages/{slug}/repositories/{id}": "读取公开页关联仓库的详情",
	"/api/github/tokens":             "列出或新增 GitHub Token",
	"/api/github/tokens/{id}":        "更新、测试或删除 GitHub Token",
	"/api/github/repositories":              "读取 GitHub 仓库列表（含刷新、webhook 配置入口）",
	"/api/github/repositories/{id}/refresh": "刷新仓库的数据与权限检测",
	"/api/github/repositories/{id}/webhook/configure": "配置仓库的 Webhook",
	"/api/github/history/compact":    "压缩并清理 GitHub 历史事件",

	// ===== 图编辑器 =====
	"/api/drawio":                    "Draw.io 图编辑器文档管理总入口",
	"/api/drawio/documents":          "列出或新建图文档",
	"/api/drawio/documents/{id}":     "更新或删除图文档",
	"/api/drawio/documents/{id}/draft": "读取或保存图文档草稿",
	"/api/drawio/documents/{id}/clone": "克隆图文档",
	"/api/drawio/documents/{id}/export": "导出图文档",
	"/api/drawio/documents/{id}/versions": "列出或保存历史版本",
	"/api/drawio/documents/{id}/versions/{versionId}": "读取指定版本详情",
	"/api/drawio/documents/{id}/versions/{versionId}/restore": "将历史版本恢复为草稿",
	"/api/drawio/documents/{id}/thumbnails/rebuild": "重建单个文档缩略图",
	"/api/drawio/import":             "导入图文件",
	"/api/drawio/thumbnails/rebuild": "批量重建全部文档缩略图",
	"/api/drawio/render-jobs":        "列出渲染任务",
	"/api/drawio/settings":           "读取或更新图编辑器设置",

	// ===== 提示词库 =====
	"/api/prompts":                    "提示词库管理总入口",
	"/api/prompts/entries":            "列出或新增提示词条目",
	"/api/prompts/entries/{id}":       "更新或删除提示词条目",
	"/api/prompts/entries/{id}/draft": "读取或保存条目草稿",
	"/api/prompts/entries/{id}/duplicate": "复制提示词条目",
	"/api/prompts/entries/{id}/publish": "发布或取消发布条目",
	"/api/prompts/entries/{id}/public/regenerate": "重新生成条目的公开 ID",
	"/api/prompts/entries/{id}/versions": "列出条目的历史版本",
	"/api/prompts/entries/{id}/versions/{versionId}": "读取指定版本",
	"/api/prompts/entries/{id}/versions/{versionId}/restore": "恢复指定版本",
	"/api/prompts/collections":        "列出或新增提示词集合",
	"/api/prompts/collections/{id}":   "更新或删除提示词集合",
	"/api/prompts/settings":           "读取或更新提示词库设置",
	"/api/prompts/public/{publicId}":  "读取公开页面的提示词数据",
	"/api/prompts/d/{publicId}":       "提示词直达链接",
	"/api/prompts/d/{publicId}/versions/{versionNo}": "提示词指定版本直达链接",

	// ===== OpenAI 网关 =====
	"/api/openai":                    "OpenAI 兼容模型网关管理总入口",
	"/api/openai/endpoints":          "列出或新增模型端点",
	"/api/openai/endpoints/{id}":     "更新或删除模型端点",
	"/api/openai/endpoints/{id}/toggle": "启用或停用模型端点",
	"/api/openai/endpoints/{id}/verify": "验证端点的 API Key 与配置",
	"/api/openai/endpoints/{id}/models": "获取端点可用的模型列表",
	"/api/openai/endpoints/{id}/models/toggle": "启用或停用端点内的单个模型",
	"/api/openai/endpoints/{id}/model-mappings": "更新端点的模型对外映射名称",
	"/api/openai/endpoints/{id}/test": "测试端点连通性",
	"/api/openai/endpoints/{id}/health-check": "对单个端点执行健康检查",
	"/api/openai/endpoints/{id}/health-check-all": "对端点执行全链路健康检查",
	"/api/openai/endpoints/{id}/key-check": "批量检测端点 API Key 有效性",
	"/api/openai/endpoints/{id}/health": "读取端点健康状态",
	"/api/openai/endpoints/refresh":  "刷新端点模型列表",
	"/api/openai/endpoints/refresh-all": "刷新全部端点的模型列表",
	"/api/openai/health-check-all":   "对所有端点执行健康检查",
	"/api/openai/export":             "导出网关配置",
	"/api/openai/import":             "导入网关配置",
	"/api/openai/analytics/summary":  "读取网关调用量汇总",
	"/api/openai/analytics/charts":   "读取网关用量图表数据",
	"/api/openai/analytics/logs":     "分页读取网关调用日志",
	"/api/openai/analytics/clear":    "清空网关调用日志（不动看板历史）",
	"/api/openai/analytics/clear-history": "清空数据看板历史（不动网关日志）",
	"/api/openai/relay-errors":       "读取最近推理转发失败明细（排障用）",
	"/api/openai/keys":               "列出或新增网关 API Key",
	"/api/openai/keys/{id}":          "更新或删除网关 API Key",
	"/api/openai/keys/{id}/toggle":   "启用或停用网关 API Key",
	"/api/openai/keys/{id}/rotate":   "轮换网关 API Key",
	"/api/openai/keys/{id}/default":  "设为默认网关 API Key",
	"/api/openai/proxies/subscription-nodes": "读取订阅板块可用的 socks/http 代理节点",
	"/api/openai/proxies/resolve-subscription": "解析订阅链接并提取 socks/http 代理节点",
	"/v1":                            "OpenAI 兼容的 /v1 推理网关入口",

	// ===== 订阅分发 =====
	"/api/subscription": "订阅分发、节点、模板、日志与设置管理总入口",
	"/sub/{token}":      "公开的 Clash / v2ray 订阅端点",

	// ===== 主机实例 server =====
	"/api/server/info":                         "读取主机实例信息",
	"/api/server/test-connection":              "测试主机连接是否可用",
	"/api/server/action":                       "对主机执行指定动作（重启、关机等）",
	"/api/server/check-all":                    "批量检查所有主机的在线状态（响应含 name，可直接识别主机）",
	"/api/server/accounts":                     "列出全部主机实例列表",
	"/api/server/accounts/{id}":                "更新或删除主机实例账号",
	"/api/server/accounts/export":              "导出主机实例账号",
	"/api/server/accounts/import":              "批量导入主机实例账号",
	"/api/server/accounts/reorder":             "调整主机实例的显示顺序",
	"/api/server/accounts/{id}/test-traffic-alert": "测试主机的流量告警",
	"/api/server/status-pages":                 "列出或新增主机状态页",
	"/api/server/status-pages/{id}":            "更新或删除主机状态页",
	"/api/server/public/status-page-by-domain": "按域名读取公开状态页",
	"/api/server/public/status-pages/{slug}":   "按 slug 读取公开状态页",
	"/api/server/s":                            "列出主机实例（简写路径）",
	"/api/server/s/{id}":                       "读取或操作单个主机（简写路径）",
	"/api/server/s/{id}/history":               "读取主机的命令历史",
	"/api/server/credentials":                  "列出或新增主机凭据",
	"/api/server/credentials/{id}":             "更新或删除主机凭据",
	"/api/server/credentials/default":          "设置默认主机凭据",
	"/api/server/credentials/{id}/default":     "将指定凭据设为默认",
	"/api/server/metrics/history":              "读取主机指标历史",
	"/api/server/metrics/history/{id}":         "读取单个主机的指标历史",
	"/api/server/metrics/latest/{id}":          "读取单个主机的最新指标",
	"/api/server/network-quality/targets":      "列出或新增测速目标",
	"/api/server/network-quality/targets/{id}": "更新或删除测速目标",
	"/api/server/network-quality/{id}":         "读取主机的网络测速结果",
	"/api/server/network-quality/{id}/collect": "触发一次网络测速采集",
	"/api/server/tasks":                        "列出或创建主机任务",
	"/api/server/tasks/{id}":                   "读取主机任务详情",
	"/api/server/tasks/{id}/stream":            "实时流式读取任务执行输出",
	"/api/server/v2/tasks":                     "创建 v2 主机任务",
	"/api/server/v2/tasks/stream":              "实时流式读取 v2 任务输出",
	"/api/server/v2/docker":                    "Docker 管理总入口",
	"/api/server/v2/docker/overview":           "Docker 容器总览",
	"/api/server/docker/check-update":          "检查容器镜像是否有更新",
	"/api/server/sftp/list":                    "列出远程目录",
	"/api/server/sftp/read":                    "读取远程文件内容",
	"/api/server/sftp/write":                   "写入远程文件",
	"/api/server/sftp/mkdir":                   "创建远程目录",
	"/api/server/sftp/rename":                  "重命名远程文件或目录",
	"/api/server/sftp/delete":                  "删除远程文件",
	"/api/server/sftp/rmdir":                   "删除远程目录",
	"/api/server/sftp/chmod":                   "修改远程文件权限",
	"/api/server/sftp/upload":                  "上传文件到远程主机",
	"/api/server/sftp/download/{serverId}":     "从远程主机下载文件",
	"/api/server/monitor/status":               "读取主机监控状态",
	"/api/server/monitor/collect":              "触发一次监控采集",
	"/api/server/monitor/config":               "读取或更新主机监控配置",
	"/api/server/monitor/logs":                 "读取主机监控日志",
	"/api/server/snippets":                     "列出或新增命令片段",
	"/api/server/snippets/{id}":                "更新或删除命令片段",
	"/api/server/snippets/preview":             "预览命令片段的渲染结果",
	"/api/server/snippets/history":             "读取命令片段的使用历史",
	"/api/server/agent/quick-install":          "快速安装主机 Agent",
	"/api/server/agent/regenerate-key":         "重新生成主机 Agent 密钥",
	"/api/server/agent/command/{id}":           "获取 Agent 安装命令（GET）或向 Agent 发送命令执行（POST）",
	"/api/server/agent/install/win/{id}/{key}": "生成 Windows 安装脚本",
	"/api/server/agent/install/linux/{id}/{key}": "生成 Linux 安装脚本",
	"/api/server/agent/install-script/{id}":    "获取主机 Agent 安装脚本",
	"/api/server/agent/heartbeat":              "接收 Agent 心跳上报",
	"/api/server/agent/status/{id}":            "查询主机 Agent 状态",
	"/api/server/agent/key":                    "读取主机 Agent 密钥",
	"/api/server/agent/key/generate":           "生成新的主机 Agent 密钥",
	"/api/server/agent/auto-install/{id}":      "自动安装主机 Agent",
	"/api/server/agent/batch-install":          "批量安装主机 Agent",
	"/api/server/agent/batch-upgrade":          "批量升级主机 Agent",
	"/api/server/agent/batch/{id}":             "查询批量安装任务状态",
	"/api/server/agent/connection-info/{id}":   "获取主机的 Agent 连接信息",
	"/api/server/agent/uninstall/{id}":         "卸载主机 Agent",
	"/api/server/agent/proxy/{id}":             "读取或更新托管代理配置",
	"/api/server/agent/proxy/{id}/reconcile":   "触发托管代理配置对账",
	"/api/server/agent/proxy/{id}/traffic":     "读取托管代理流量统计",
	"/api/server/agent/proxy/nodes":            "列出或新增托管代理节点",
	"/api/server/agent/proxy/nodes/{id}":       "更新或删除托管代理节点",
	"/api/server/agent/proxy/nodes/{id}/reconcile": "触发代理节点对账",
	"/api/server/agent/proxy/tunnels":          "列出或新增托管隧道",
	"/api/server/agent/proxy/tunnels/{serverId}": "读取或删除托管隧道",
	"/api/server/agent/proxy/tunnels/{serverId}/deploy": "部署托管隧道",
	"/api/server/agent/proxy/tunnels/preflight": "托管隧道部署前检查",
	"/api/server/agent/proxy/preferred-addresses": "列出或新增优选地址",
	"/api/server/agent/proxy/preferred-addresses/{id}": "更新或删除优选地址",
	"/api/server/agent/proxy/preferred-addresses/{id}/check": "检测优选地址连通性",
	"/api/server/agent/proxy/runtimes":         "列出或注册代理运行时",
	"/api/server/agent/proxy/runtimes/{id}/{action}": "对代理运行时执行安装 / 更新等动作",
	"/api/server/remote-desktop/sessions":      "创建远程桌面会话",
	"/api/server/remote-desktop/sessions/{id}": "查询或关闭远程桌面会话",
	"/api/server/remote-desktop/sessions/{id}/signals": "发送远程桌面控制信号（鼠标 / 键盘）",
	"/ws/ssh":                                  "SSH 终端 WebSocket 连接",
	"/ws/agent-terminal":                       "Agent 终端 WebSocket 连接",
	"/socket.io/":                              "Socket.IO 实时通信通道",
}

