import { useRef } from 'react';
import { useConfirmPress } from '../../hooks/useConfirmPress.js';
import { useEndpointCrud, sortEndpoints } from './useEndpoints/useEndpointCrud.js';
import { useEndpointModels } from './useEndpoints/useEndpointModels.js';
import { useEndpointForm } from './useEndpoints/useEndpointForm.js';

export { sortEndpoints };

// useEndpoints：端点 CRUD/排序/模型开关与批量/代理池/导入导出/模型映射/模型列表。
export function useEndpoints() {
  const confirmState = useConfirmPress();
  const modelsRef = useRef(null);
  const crudApi = useEndpointCrud({
    loadAllModels: (...args) => modelsRef.current.loadAllModels(...args),
    routingEditKeyState: {
      setRoutingEditKey: (...args) => modelsRef.current.setRoutingEditKey(...args),
    },
    confirmState,
  });
  const modelApi = useEndpointModels({ setEndpoints: crudApi.setEndpoints });
  modelsRef.current = modelApi;
  const formApi = useEndpointForm({
    loadEndpoints: crudApi.loadEndpoints,
    loadAllModels: modelApi.loadAllModels,
    confirmState,
  });

  return {
    endpoints: crudApi.endpoints,
    setEndpoints: crudApi.setEndpoints,
    endpointsLoading: crudApi.endpointsLoading,
    setEndpointsLoading: crudApi.setEndpointsLoading,
    endpointsRefreshing: crudApi.endpointsRefreshing,
    setEndpointsRefreshing: crudApi.setEndpointsRefreshing,
    endpointToggleLoading: crudApi.endpointToggleLoading,
    setEndpointToggleLoading: crudApi.setEndpointToggleLoading,
    selectedEndpointId: crudApi.selectedEndpointId,
    setSelectedEndpointId: crudApi.setSelectedEndpointId,
    endpointFormOpen: formApi.endpointFormOpen,
    setEndpointFormOpen: formApi.setEndpointFormOpen,
    editingEndpoint: formApi.editingEndpoint,
    setEditingEndpoint: formApi.setEditingEndpoint,
    endpointForm: formApi.endpointForm,
    setEndpointForm: formApi.setEndpointForm,
    endpointFormError: formApi.endpointFormError,
    setEndpointFormError: formApi.setEndpointFormError,
    endpointSaving: formApi.endpointSaving,
    setEndpointSaving: formApi.setEndpointSaving,
    endpointKeyChecks: formApi.endpointKeyChecks,
    setEndpointKeyChecks: formApi.setEndpointKeyChecks,
    endpointKeyChecking: formApi.endpointKeyChecking,
    setEndpointKeyChecking: formApi.setEndpointKeyChecking,
    loadEndpoints: crudApi.loadEndpoints,
    endpointImportInputRef: crudApi.endpointImportInputRef,
    endpointImporting: crudApi.endpointImporting,
    setEndpointImporting: crudApi.setEndpointImporting,
    importModeDialog: crudApi.importModeDialog,
    setImportModeDialog: crudApi.setImportModeDialog,
    endpointExporting: crudApi.endpointExporting,
    setEndpointExporting: crudApi.setEndpointExporting,
    exportEndpoints: crudApi.exportEndpoints,
    importEndpointsFromFile: crudApi.importEndpointsFromFile,
    runEndpointImport: crudApi.runEndpointImport,
    selectedEndpoint: crudApi.selectedEndpoint,
    enabledModelCount: crudApi.enabledModelCount,
    verifyEndpoint: crudApi.verifyEndpoint,
    refreshEndpointModels: crudApi.refreshEndpointModels,
    refreshAllEndpoints: crudApi.refreshAllEndpoints,
    toggleEndpointEnabled: crudApi.toggleEndpointEnabled,
    saveEndpointRouting: crudApi.saveEndpointRouting,
    modelSwitchLoadingRef: modelApi.modelSwitchLoadingRef,
    modelSwitchLoading: modelApi.modelSwitchLoading,
    setModelSwitchLoading: modelApi.setModelSwitchLoading,
    toggleModelEnabled: modelApi.toggleModelEnabled,
    modelEnabledForEndpoint: modelApi.modelEnabledForEndpoint,
    openAddEndpointModal: formApi.openAddEndpointModal,
    openEditEndpointModal: formApi.openEditEndpointModal,
    updateEndpointProxy: formApi.updateEndpointProxy,
    addEndpointProxy: formApi.addEndpointProxy,
    removeEndpointProxy: formApi.removeEndpointProxy,
    proxyBatchOpen: formApi.proxyBatchOpen,
    setProxyBatchOpen: formApi.setProxyBatchOpen,
    proxyBatchText: formApi.proxyBatchText,
    setProxyBatchText: formApi.setProxyBatchText,
    proxyImportLoading: formApi.proxyImportLoading,
    setProxyImportLoading: formApi.setProxyImportLoading,
    subscriptionUrlOpen: formApi.subscriptionUrlOpen,
    setSubscriptionUrlOpen: formApi.setSubscriptionUrlOpen,
    subscriptionUrl: formApi.subscriptionUrl,
    setSubscriptionUrl: formApi.setSubscriptionUrl,
    editingProxyIndex: formApi.editingProxyIndex,
    setEditingProxyIndex: formApi.setEditingProxyIndex,
    proxyManagerOpen: formApi.proxyManagerOpen,
    setProxyManagerOpen: formApi.setProxyManagerOpen,
    manualProxyEntries: formApi.manualProxyEntries,
    saveProxyBatch: formApi.saveProxyBatch,
    addProxyBatch: formApi.addProxyBatch,
    proxyFileInputRef: formApi.proxyFileInputRef,
    importProxyFile: formApi.importProxyFile,
    expandedBatchId: formApi.expandedBatchId,
    setExpandedBatchId: formApi.setExpandedBatchId,
    manualProxyExpanded: formApi.manualProxyExpanded,
    setManualProxyExpanded: formApi.setManualProxyExpanded,
    proxyRuntimeStates: formApi.proxyRuntimeStates,
    setProxyRuntimeStates: formApi.setProxyRuntimeStates,
    disabledProxyUntil: formApi.disabledProxyUntil,
    disabledProxyCount: formApi.disabledProxyCount,
    unbanningProxies: formApi.unbanningProxies,
    setUnbanningProxies: formApi.setUnbanningProxies,
    unbanAllProxies: formApi.unbanAllProxies,
    probingProxies: formApi.probingProxies,
    setProbingProxies: formApi.setProbingProxies,
    probeAllProxies: formApi.probeAllProxies,
    removeProxyBatch: formApi.removeProxyBatch,
    removeProxyFromBatch: formApi.removeProxyFromBatch,
    resolveSubscriptionProxies: formApi.resolveSubscriptionProxies,
    updateEndpointHeader: formApi.updateEndpointHeader,
    addEndpointHeader: formApi.addEndpointHeader,
    removeEndpointHeader: formApi.removeEndpointHeader,
    saveEndpoint: formApi.saveEndpoint,
    checkEndpointKeys: formApi.checkEndpointKeys,
    appendEndpointKey: formApi.appendEndpointKey,
    removeEndpointKey: formApi.removeEndpointKey,
    keyDeleteConfirmActive: formApi.keyDeleteConfirmActive,
    deleteEndpointConfirmActive: crudApi.deleteEndpointConfirmActive,
    deleteEndpoint: crudApi.deleteEndpoint,
    allModels: modelApi.allModels,
    setAllModels: modelApi.setAllModels,
    loadAllModels: modelApi.loadAllModels,
    mappingEditKey: modelApi.mappingEditKey,
    setMappingEditKey: modelApi.setMappingEditKey,
    mappingDraft: modelApi.mappingDraft,
    setMappingDraft: modelApi.setMappingDraft,
    routingEditKey: modelApi.routingEditKey,
    setRoutingEditKey: modelApi.setRoutingEditKey,
    routingDraft: modelApi.routingDraft,
    setRoutingDraft: modelApi.setRoutingDraft,
    batchToggleEndpointModels: modelApi.batchToggleEndpointModels,
    saveEndpointMapping: modelApi.saveEndpointMapping,
    batchEnableDisabledModels: modelApi.batchEnableDisabledModels,
    addEndpointModels: modelApi.addEndpointModels,
  };
}
