import React from 'react';

export const BRAND_COLOR_FALLBACK = '#8b5cf6';
export const BRAND_ICON_FALLBACK = 'fas fa-shield-alt';

export const ISSUER_COLORS = {
  github: '#6e40c9',
  gitlab: '#fc6d26',
  bitbucket: '#0052cc',
  discord: '#5865f2',
  twitter: '#1da1f2',
  'x.com': '#000000',
  facebook: '#1877f2',
  instagram: '#e4405f',
  linkedin: '#0a66c2',
  reddit: '#ff4500',
  telegram: '#26a5e4',
  whatsapp: '#25d366',
  slack: '#4a154b',
  twitch: '#9146ff',
  microsoft: '#00a4ef',
  google: '#4285f4',
  amazon: '#ff9900',
  apple: '#000000',
  meta: '#1877f2',
  cloudflare: '#f38020',
  vultr: '#007bfc',
  digitalocean: '#0080ff',
  linode: '#00a95c',
  heroku: '#430098',
  vercel: '#000000',
  netlify: '#00c7b7',
  railway: '#0b0d0e',
  render: '#46e3b7',
  dropbox: '#0061ff',
  steam: '#1b2838',
  epic: '#2f2d2e',
  playstation: '#003791',
  xbox: '#107c10',
  nintendo: '#e60012',
  blizzard: '#00ceff',
  paypal: '#003087',
  stripe: '#635bff',
  coinbase: '#0052ff',
  binance: '#f0b90b',
  tencent: '#1296db',
  huawei: '#cf0a2c',
  aliyun: '#ff6a00',
  alibaba: '#ff6a00',
};

export const SIMPLE_ICONS = {
  github: 'si si-github',
  gitlab: 'si si-gitlab',
  bitbucket: 'si si-bitbucket',
  discord: 'si si-discord',
  twitter: 'si si-twitter',
  'x.com': 'si si-x',
  facebook: 'si si-facebook',
  instagram: 'si si-instagram',
  linkedin: 'si si-linkedin',
  reddit: 'si si-reddit',
  telegram: 'si si-telegram',
  whatsapp: 'si si-whatsapp',
  slack: 'si si-slack',
  twitch: 'si si-twitch',
  microsoft: 'fab fa-microsoft',
  google: 'si si-google',
  amazon: 'si si-amazon',
  apple: 'si si-apple',
  meta: 'si si-meta',
  cloudflare: 'si si-cloudflare',
  aws: 'si si-amazonaws',
  digitalocean: 'si si-digitalocean',
  vultr: 'si si-vultr',
  linode: 'si si-linode',
  heroku: 'si si-heroku',
  vercel: 'si si-vercel',
  netlify: 'si si-netlify',
  railway: 'si si-railway',
  render: 'si si-render',
  dropbox: 'si si-dropbox',
  drive: 'si si-googledrive',
  onedrive: 'si si-microsoftonedrive',
  backblaze: 'si si-backblaze',
  steam: 'si si-steam',
  epic: 'si si-epicgames',
  playstation: 'si si-playstation',
  xbox: 'si si-xbox',
  nintendo: 'si si-nintendo',
  blizzard: 'si si-blizzard',
  ubisoft: 'si si-ubisoft',
  paypal: 'si si-paypal',
  stripe: 'si si-stripe',
  coinbase: 'si si-coinbase',
  binance: 'si si-binance',
  npm: 'si si-npm',
  docker: 'si si-docker',
  wordpress: 'si si-wordpress',
  jira: 'si si-jira',
  trello: 'si si-trello',
  figma: 'si si-figma',
  notion: 'si si-notion',
  tencent: 'fab fa-qq',
  huawei: 'si si-huawei',
  aliyun: 'si si-alibabacloud',
  alibaba: 'si si-alibaba',
  baidu: 'si si-baidu',
  weixin: 'si si-wechat',
  wechat: 'si si-wechat',
  weibo: 'si si-sinaweibo',
  qq: 'fab fa-qq',
  bytedance: 'si si-bytedance',
  douyin: 'si si-tiktok',
  bilibili: 'si si-bilibili',
  spaceship: 'si si-spaceship',
  godaddy: 'si si-godaddy',
  namecheap: 'si si-namecheap',
  porkbun: 'si si-porkbun',
  bitwarden: 'si si-bitwarden',
  '1password': 'si si-1password',
  lastpass: 'si si-lastpass',
  proton: 'si si-proton',
  shopify: 'si si-shopify',
  spotify: 'si si-spotify',
  adobe: 'si si-adobe',
  zoom: 'si si-zoom',
  okta: 'si si-okta',
  auth0: 'si si-auth0',
  hetzner: 'si si-hetzner',
  ovh: 'si si-ovh',
  oracle: 'si si-oracle',
  sentry: 'si si-sentry',
  cloudways: 'si si-cloudways',
};

export const FA_ICONS = {
  microsoft: 'fab fa-microsoft',
  github: 'fab fa-github',
  google: 'fab fa-google',
  amazon: 'fab fa-amazon',
  apple: 'fab fa-apple',
  dropbox: 'fab fa-dropbox',
  steam: 'fab fa-steam',
  playstation: 'fab fa-playstation',
  xbox: 'fab fa-xbox',
  paypal: 'fab fa-paypal',
  stripe: 'fab fa-stripe',
  docker: 'fab fa-docker',
  npm: 'fab fa-npm',
  discord: 'fab fa-discord',
  twitter: 'fab fa-twitter',
  facebook: 'fab fa-facebook',
  instagram: 'fab fa-instagram',
  linkedin: 'fab fa-linkedin',
  reddit: 'fab fa-reddit',
  telegram: 'fab fa-telegram',
  whatsapp: 'fab fa-whatsapp',
  slack: 'fab fa-slack',
  twitch: 'fab fa-twitch',
  spotify: 'fab fa-spotify',
  adobe: 'fab fa-adobe',
  cloudflare: 'fas fa-cloud',
  vultr: 'fas fa-server',
  digitalocean: 'fab fa-digital-ocean',
  linux: 'fab fa-linux',
  ubuntu: 'fab fa-ubuntu',
  windows: 'fab fa-windows',
  email: 'fas fa-envelope',
  mail: 'fas fa-envelope',
  bank: 'fas fa-university',
  crypto: 'fas fa-coins',
  vpn: 'fas fa-shield-alt',
  server: 'fas fa-server',
  hosting: 'fas fa-server',
  domain: 'fas fa-globe',
  ssh: 'fas fa-terminal',
  database: 'fas fa-database',
  storage: 'fas fa-hdd',
  cloud: 'fas fa-cloud',
  game: 'fas fa-gamepad',
  shop: 'fas fa-shopping-cart',
  store: 'fas fa-store',
  finance: 'fas fa-chart-line',
  trading: 'fas fa-chart-bar',
  exchange: 'fas fa-exchange-alt',
  wallet: 'fas fa-wallet',
  social: 'fas fa-users',
  chat: 'fas fa-comments',
  video: 'fas fa-video',
  photo: 'fas fa-camera',
  code: 'fas fa-code',
  dev: 'fas fa-laptop-code',
};

function findIssuerMatch(issuer, source) {
  const key = issuer?.toLowerCase() || '';
  return Object.entries(source).find(([name]) => key.includes(name))?.[1];
}

export function getIssuerColor(issuer) {
  return findIssuerMatch(issuer, ISSUER_COLORS) || BRAND_COLOR_FALLBACK;
}

export function getIssuerIcon(issuer) {
  return findIssuerMatch(issuer, SIMPLE_ICONS)
    || findIssuerMatch(issuer, FA_ICONS)
    || BRAND_ICON_FALLBACK;
}

export default function BrandIcon({ issuer, className = '', style, ...props }) {
  return (
    <i
      {...props}
      className={`${getIssuerIcon(issuer)} ${className}`.trim()}
      style={{ color: getIssuerColor(issuer), ...style }}
    />
  );
}
